JFLAGS = -d out -cp lox 
JC = javac
.SUFFIXES: .java .class
.java.class:
	$(JC) $(JFLAGS) $*.java

# This uses the line continuation character (\) for readability
# You can list these all on a single line. separated by a space insted.
# If your version of make can't handle the leading tabs on each
# line, just remove them (these are also just added for readability).
CLASSES = \
		  lox/TokenType.java \
		  lox/Token.java \
		  lox/Scanner.java \
		  lox/Lox.java

default: classes

classes: $(CLASSES:.java=.class)

clean:
		$(RM) *.class
